spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yml
  thymeleaf:
    cache: false